[build]
  command = "./drush.phar deploy --debug && ./composer.phar install --debug"
  commandOrigin = "config"
[build.environment]
  PHP_VERSION = "8.1"
  DRUSH_SITE_ALIAS = "your-site-alias"
  publish = "/opt/build/repo/web"
  repo = "url = https://github.com/MikeTarica/mike-website-drupal.git"
  branch = "main"
  

  publishOrigin = "config"
  redirectsPath = "web/_redirects"
  headersPath = "web/_headers"

[scripts]
  install-composer = "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\" && php composer-setup.php && php -r \"unlink('composer-setup.php');\""
  install-drush = "wget -q -O drush.phar https://github.com/drush-ops/drush/releases/download/10.3.0/drush.phar && chmod +x drush.phar"
