[build]
  command = "curl -sS https://getcomposer.org/installer | php && php composer.phar install && drush deploy"
  commandOrigin = "config"
  environment = [
    "PHP_VERSION",
    "DRUSH_SITE_ALIAS"
  ]
  publish = "/opt/build/repo/web"
  publishOrigin = "config"

  command = "composer install && curl -sS https://github.com/drush-ops/drush/releases/download/10.3.0/drush.phar -o drush && chmod +x drush && ./drush deploy"
  commandOrigin = "config"
  environment = [
    "PHP_VERSION",
    "DRUSH_SITE_ALIAS"
  ]
  publish = "/opt/build/repo/web"
  publishOrigin = "config"