[build]
  command = "php composer.phar install"
  commandOrigin = "config"
  environment = [
    "PHP_VERSION",
    "DRUSH_SITE_ALIAS"
  ]
  publish = "/opt/build/repo/opt/build/repo/web"
  publishOrigin = "config"
  redirectsPath = "/opt/build/repo/opt/build/repo/web/_redirects"
  headersPath = "/opt/build/repo/opt/build/repo/web/_headers"
  script = "install-drush"