[build]
  command = "composer install && drush deploy"
  publish = "web"
  base = "."

[scripts]
  install = "composer install"
  postinstall = "drush site-install --yes"
  prebuild = "drush cr"
  postbuild = "drush deploy"

[context.production]
  environment = { DRUPAL_ENV = "prod" }
  command = "composer install && drush deploy --prod"

[context.staging]
  environment = { DRUPAL_ENV = "stg" }
  command = "composer install && drush deploy --stg"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[plugins]
  plugins = ["netlify-plugin-drupal"]

[deploy]
  hook = "drush deploy"

# [build]
#   command = "composer install && drush deploy"
#   publish = "web"
#   base = "."

# [build.environment]
#   PHP_VERSION = "8.1"
#   DRUSH_SITE_ALIAS = "your-site-alias"
#   publish = "/opt/build/repo/web"
#   repo = "url = https://github.com/MikeTarica/mike-website-drupal.git"
#   branch = "main"


#   publishOrigin = "config"
#   redirectsPath = "web/_redirects"
#   headersPath = "web/_headers"

# [scripts]
#   install = "composer install"
#   postinstall = "drush site-install --yes"
#   prebuild = "drush cr"
#   postbuild = "drush deploy"