[build]
  command = "php composer.phar install"
  commandOrigin = "config"
  environment = [
    "PHP_VERSION",
    "DRUSH_SITE_ALIAS"
  ]
  publish = "/opt/build/repo/web"
  publishOrigin = "config"
  script = "install-drush"

[scripts]
  install-drush = "13.0.1 -sS https://github.com/drush-ops/drush/releases/download/10.3.0/drush.phar -o drush && chmod +x drush"
  install-composer = "curl -sS https://getcomposer.org/installer | php"