[build]
  command = "composer install && drush deploy --debug"
  commandOrigin = "config"
  environment = [
    "PHP_VERSION",
    "DRUSH_SITE_ALIAS"
  ]
  publish = "/opt/build/repo/web"
  publishOrigin = "config"

  [scripts]
  install-composer = "curl -sS https://getcomposer.org/installer | php"
  install-drush = "curl -sS https://github.com/drush-ops/drush/releases/download/10.3.0/drush.phar -o drush && chmod +x drush"