<?php

/**
 * @file
 * Provides options for 'Long Text With Summary' widget.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_form_FORM_ID_form_alter().
 */
function text_summary_options_form_field_config_edit_form_alter(array &$form, FormStateInterface $form_state): void {
  $field = $form_state->getFormObject()->getEntity();

  if ($field->getType() == 'text_with_summary') {
    $form['third_party_settings']['text_summary_options'] = [
      '#type' => 'container',
      '#tree' => TRUE,
    ];
    $form['third_party_settings']['text_summary_options']['show_summary'] = [
      '#type' => 'checkbox',
      '#title' => t('Show summary'),
      '#default_value' => (int) $field->getThirdPartySetting('text_summary_options', 'show_summary'),
      '#description' => t('Display the summary field by default.'),
    ];

    $form['third_party_settings']['text_summary_options']['summary_help'] = [
      '#type' => 'textarea',
      '#title' => t('Summary help text'),
      '#description' => t('Help text to display for the summary.'),
      '#default_value' => $field->getThirdPartySetting('text_summary_options', 'summary_help'),
    ];

    $form['third_party_settings']['text_summary_options']['summary_placeholder'] = [
      '#type' => 'textarea',
      '#title' => t('Summary Placeholder'),
      '#description' => t('Placeholder text to display for the summary.'),
      '#default_value' => $field->getThirdPartySetting('text_summary_options', 'summary_placeholder'),
    ];
  }
}

/**
 * Implements hook_field_widget_single_element_form_alter().
 */
function text_summary_options_field_widget_single_element_form_alter(array &$element, FormStateInterface $form_state, array $context): void {

  $field_definition = $context['items']->getFieldDefinition();

  // Base fields are not configurable.
  if (!$field_definition instanceof FieldConfig) {
    return;
  }

  // We can't use the protected isDefaultValueWidget() method.
  $is_default_value_widget = (bool) $form_state->get('default_value_widget');

  if ($field_definition->getType() == 'text_with_summary' && !$is_default_value_widget) {
    $field_configuration = $field_definition->getConfig($field_definition->getTargetBundle());

    $show_summary_setting = (int) $field_configuration->getThirdPartySetting('text_summary_options', 'show_summary');
    $summary_help_setting = $field_configuration->getThirdPartySetting('text_summary_options', 'summary_help');

    if ($show_summary_setting) {
      unset($element['summary']['#attached']);
    }

    if (!empty($summary_help_setting)) {
      $element['summary']['#description'] = $summary_help_setting;
    }

    $summary_placeholder_setting = $field_configuration->getThirdPartySetting('text_summary_options', 'summary_placeholder');

    if (!empty($summary_placeholder_setting)) {
      $element['summary']['#attributes']['placeholder'] = [$summary_placeholder_setting];
    }
  }
}
